#!/usr/bin/expect -f
set timeout 60
set host "72.61.229.171"
set user "root"
set password ")vbofQi/lHXSMqF?Nk8E"
spawn ssh -o StrictHostKeyChecking=no $user@$host "sed -i 's/GOOGLE_API_KEY=.*/GOOGLE_API_KEY=AIzaSyBXo8LG4ICAN9U8kyUgeY_OT8nKMIVO6Es/' /var/www/qr.akmal.in/.env.local && cd /var/www/qr.akmal.in && pm2 restart qr-frontend"
expect {
    "password:" {
        send "$password\r"
    }
}
expect eof
